<template>
  <div class="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" @click.self="$emit('close')">
    <div class="bg-white dark:bg-gray-900 rounded-2xl shadow-2xl w-full max-w-md overflow-hidden flex flex-col animate-in zoom-in-95 duration-200">
      <div class="p-6 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between bg-gray-50 dark:bg-gray-800">
        <div class="flex items-center gap-3">
          <div class="p-2 bg-amber-100 dark:bg-amber-900/30 rounded-lg">
            <AlertTriangle :size="20" class="text-amber-600 dark:text-amber-500" />
          </div>
          <h2 class="text-lg font-bold text-gray-900 dark:text-white">Data Accuracy Disclaimer</h2>
        </div>
        <button @click="$emit('close')" class="text-gray-400 dark:text-gray-500 hover:text-gray-900 dark:hover:text-white transition-colors">
          <X :size="20" />
        </button>
      </div>
      
      <div class="p-6 space-y-4 text-sm text-gray-600 dark:text-gray-300 leading-relaxed">
        <p>
          Please be aware that all terrain data, heightmaps, and 3D models generated by MapNG are <span class="font-bold text-gray-900 dark:text-white">estimations</span> based on available satellite and elevation datasets.
        </p>
        
        <div class="bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-900/30 rounded-lg p-4 text-amber-900 dark:text-amber-100 text-xs">
          <p class="font-medium mb-1">Resolution & Scale</p>
          <p>All heightmaps are exported at 1 meter per pixel resolution to ensure consistent scaling in game engines. However, when using the Standard (30m) dataset, the terrain is upsampled. This means it will be smooth but lack the fine details found in true 1m datasets like USGS or GPXZ.</p>
        </div>

        <p class="text-xs text-gray-500 dark:text-gray-400">
          This tool is intended for modding and creative use. It should not be used for navigation, engineering, or critical real-world planning.
        </p>

        <button 
          @click="$emit('close')"
          class="w-full py-2.5 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-medium rounded-lg hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors mt-2"
        >
          I Understand
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { AlertTriangle, X } from 'lucide-vue-next';

defineEmits(['close']);
</script>
